name: task_manager_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  freezed_annotation: ^2.4.1
  pretty_dio_logger: ^1.1.1
  reactive_color_picker: ^0.4.0
  reactive_forms: ^14.1.0
  hydrated_bloc: ^9.1.5
  path_provider: ^2.1.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.2
  json_serializable: ^6.3.1

flutter:

  uses-material-design: true
